export const ADMIN_GET_COLL_FAIL = "ADMIN_GET_COLL_FAIL";
export const ADMIN_GET_COLL_REQUEST = "ADMIN_GET_COLL_REQUEST";

export const ADMIN_ADD_COLL_FAIL = "ADMIN_ADD_COLL_FAIL";
export const ADMIN_ADD_COLL_REQUEST = "ADMIN_ADD_COLL_REQUEST ";

export const ADMIN_DEL_COLL_FAIL = " ADMIN_DEL_COLL_FAIL";
export const ADMIN_DEL_COLL_REQUEST = "ADMIN_DEL_COLL_REQUEST";

export const ADMIN_SEND_EMAIL_FAIL = " ADMIN_SEND_EMAIL_FAIL";
export const ADMIN_SEND_EMAIL_REQUEST = " ADMIN_SEND_EMAIL_REQUEST";

export const ADMIN_ADD_QCM_FAIL = "ADMIN_ADD_QCM_FAIL";
export const ADMIN_ADD_QCM_REQUEST = "ADMIN_ADD_QCM_REQUEST";


export const ADMIN_GET_QCM_FAIL = "ADMIN_GET_QCM_FAIL";
export const ADMIN_GET_QCM_REQUEST = "ADMIN_GET_QCM_REQUEST";


export const ADMIN_GET_ONE_QCM_FAIL = "ADMIN_GET_ONE_QCM_FAIL";
export const ADMIN_GET_ONE_QCM_REQUEST = "ADMIN_GET_ONE_QCM_REQUEST";
