
export const COLL_ADD_CAND_FAIL = "COLL_ADD_CAND_FAIL";
export const COLL_ADD_CAND_REQUEST = "COLL_ADD_CAND_REQUEST";

export const COLL_GET_CAND_FAIL = "COLL_GET_CAND_FAIL";
export const COLL_GET_CAND_REQUEST = "COLL_GET_CAND_REQUEST ";

export const COLL_UP_FILE_FAIL = "COLL_UP_FILE_FAIL3";
export const COLL_UP_FILE_REQUEST = "COLL_UP_FILE_REQUEST";

export const COLL_EXPORT_DATA_FAIL = "COLL_EXPORT_DATA_FAIL";
export const COLL_EXPORT_DATA_REQUEST = "COLL_EXPORT_DATA_REQUEST";

export const COLL_ADD_TEST_FAIL = "COLL_ADD_TEST_FAIL ";
export const COLL_ADD_TEST_REQUEST = "COLL_ADD_TEST_REQUEST ";

export const COLL_SEND_TEST_FAIL = "COLL_SEND_TEST_FAIL ";
export const COLL_SEND_TEST_REQUEST = "COLL_SEND_TEST_REQUEST";