/****users****/
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_RESET_PASSWORD_FAIL = "USER_REST_PASSWORD_FAIL";
export const USER_RESET_PASSWORD_REQUEST = "USER_RESET_PASSWORD_REQUEST";

export const USER_EDIT_PROFILE_FAIL = "USER_EDIT_PROFILE_FAIL";
export const USER_EDIT_PROFILE_REQUEST = "USER_EDIT_PROFILE_REQUEST";
